name: Publish to Image Registry

on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            supabase/deno-relay
            public.ecr.aws/supabase/deno-relay
            ghcr.io/supabase/deno-relay
          flavor: latest=false
          tags: |
            type=raw,value=${{ inputs.version }}
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE }}
          aws-region: us-east-1
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
